---
title: "Covariates subset and finite samples"
author:
  - Bénédicte Colnet [Inria, Paris-Saclay]
date: "September 2021"
output:
  html_document:
    code_folding: "hide"
    number_sections: no
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
abstract: | 
  This notebook follows Judith's analysis on AIPW. 
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Reproducibility
set.seed(123)

# Libraries
library(dplyr) # case_when and others
library(ggplot2)
library(tidyr) # pivot
library(grf)
library(glmnet)
library(ranger) # efficient forest
library(splines) # function bs() for splines


# simulation set up according to Wager & Nie
generate_simulation_wager <- function(n = 1000, p = 12, setup = "D"){
  
  # set-ups
  if (setup == "A"){
    X = matrix(runif(n*p, min=0, max=1), n, p)
    b = sin(pi * X[,2] * X[,3]) + 2 * (X[,4] - 0.5)^2 + X[,5] + 0.5 * X[,6]
    eta = 0.1
    e = pmax(eta, pmin(sin(pi * X[,1] * X[,2] * X[,3]), 1-eta))
    tau = (X[,3] + X[,4]) / 2
  } else if (setup == "B"){
    X = matrix(rnorm(n * p), n, p)
    b = pmax(0, X[,2] + X[,3], X[,4]) + pmax(0, X[,5] + X[,6])
    e = 0.5
    tau = X[,2] + log(1 + exp(X[,3]))
  } else if (setup == "C") {
    X = matrix(rnorm(n * p), n, p)
    b = 2 * log(1 + exp(X[,2] + X[,3] + X[,4]+ X[,5]+ X[,6]))
    e = 1/(1 + exp(X[,1] + X[,2] + X[,3]))
    tau = rep(1, n)
  } else if (setup == "D") {
    X = matrix(rnorm(n*p), n, p)
    b = (pmax(X[,2] + X[,3] + X[,4], 0) + pmax(X[,5] + X[,6], 0)) / 2
    e = 1/(1 + exp(-X[,1]) + exp(-X[,2] + exp(-X[,3])))
    tau = pmax(X[,2] + X[,3] + X[,4], 0) - pmax(X[,5] + X[,6], 0)
  } else if (setup == "simple"){
    X = matrix(rnorm(n*p), n, p)
    b = X[,2] 
    e = 1/(1 + exp(-X[,1]) + exp(-X[,2] + exp(-X[,3])))
    tau = X[,3] + X[,4] + X[,5] + X[,6]
  } else {
    print("error in setup")
    break
  }
  
  # complete potential outcomes, treatment, and observed outcome
  simulation <- data.frame(X = X, b = b, tau = tau, e = e)
  simulation$Y_0 <- simulation$b - 0.5*simulation$tau + rnorm(n, mean = 0, sd = 0.1)
  simulation$Y_1 <- simulation$b + 0.5*simulation$tau + rnorm(n, mean = 0, sd = 0.1)
  simulation$A <- rbinom(n, size = 1, prob = simulation$e)
  simulation$Y <- ifelse(simulation$A == 1, simulation$Y_1, simulation$Y_0)
  
  return(simulation)
}


# # Empirically compute true ATEs
# a_big_simulation <- generate_simulation(n = 50000, setup = "A")
# ATE_A <- mean(a_big_simulation$Y_1) - mean(a_big_simulation$Y_0)
# 
# a_big_simulation <- generate_simulation(n = 50000, setup = "B")
# ATE_B <- mean(a_big_simulation$Y_1) - mean(a_big_simulation$Y_0)
# 
# a_big_simulation <- generate_simulation(n = 50000, setup = "C")
# ATE_C <- mean(a_big_simulation$Y_1) - mean(a_big_simulation$Y_0)
# 
# a_big_simulation <- generate_simulation(n = 50000, setup = "D")
# ATE_D <- mean(a_big_simulation$Y_1) - mean(a_big_simulation$Y_0)
# 
# 
# ATE <- c("A" = ATE_A, 
#          "B" = ATE_B,
#          "C" = ATE_C,
#          "D" = ATE_D)
```




```{r}
# simulation set up according to Wager & Nie
generate_simulation_simple <- function(n = 1000, p = 10){
  
  X = matrix(rnorm(n*p), n, p)
  b = X[,3] + X[,4] + X[,5] + X[,6]
  e =  1/(1 + exp(-X[,1]) + exp(-X[,2] + exp(-X[,3]) + exp(-X[,4]) + exp(-X[,5])))
  tau = (X[,3] + X[,4] +X[,5] ) 
  
  # complete potential outcomes, treatment, and observed outcome
  simulation <- data.frame(X = X, b = b, tau = tau, e = e)
  simulation$Y_0 <- simulation$b - 0.5*simulation$tau + rnorm(n, mean = 0, sd = 0.1)
  simulation$Y_1 <- simulation$b + 0.5*simulation$tau + rnorm(n, mean = 0, sd = 0.1)
  simulation$A <- rbinom(n, size = 1, prob = simulation$e)
  simulation$Y <- ifelse(simulation$A == 1, simulation$Y_1, simulation$Y_0)
  
  return(simulation)
}

simulation <- generate_simulation_simple()
```



```{r}
results <- read.csv("./data/2021-10-12-aipw-forest.csv")
```

```{r}
results$sample.size <- as.factor(results$sample.size)
```


```{r}
setup = "A"
ggplot(results[results$simulation == setup,], aes(x = sample.size, y = estimate, fill = estimator)) +
  geom_boxplot() +
  geom_hline(yintercept = ATE[setup], color = "blue", alpha = 0.5) +
  theme_minimal() +
  facet_grid(subset~estimator) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1),
        legend.position="none") +
  ggtitle(paste0("Set-up ", setup))
```




